# Generated by Django 3.1.5 on 2021-01-10 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('phone', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('employee_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('organizatioin', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('phone', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('source_of_leads', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type_of_interaction', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_interaction', models.DateField(blank=True, null=True)),
                ('time_of_interaction', models.CharField(blank=True, max_length=50, null=True)),
                ('interaction_detail', models.TextField(blank=True, null=True)),
                ('score', models.CharField(blank=True, max_length=50, null=True)),
                ('assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='leads.salesperson')),
            ],
        ),
    ]
